### ISSUE TITLE
travis always failed: PR always rejected

### ISSUE THREAD

**Issue by tomlemeuch** [OpenClassrooms-Student-Center/alumnis#584]
For a couple of days all pull requests are rejected because of travis test failure.
First it was a problem with meta data. Then the problem seems to be a parsing error in jeanfrancois13.md file.
But nodody here can afford to change the file of this students. I tried to check what is wrong in this file but line 6 and 37 seem to be OK.

Could you check what is wrong please so that we could  make PR again.

Thank you and have a nice day.

**Comment by papsiii** [comment]
I have the same problem..  : /

**Comment by teksaver** [comment]
Hi, I reverted the commit that started the failures - could someone resubmit a pull request?

**Comment by tomlemeuch** [comment]
thank you travis tests are OK again!

**Comment by tomlemeuch** [comment]
Is there a defined time each day for PR merging after travis tests validation?

**Comment by celine-m-s** [comment]
Hello!
There is no defined time after a PR, all tests run on a queue basis.
Just as a reminder, Travis will run when:
- a new PR is made. It will run tests and show if they succeeded or failed.
- a new commit is made for an existing PR. Again, tests will run and Travis will show on the PR page if it succeeded or failed.
- after a PR is merged into master. This time, Travis will show nothing on the PR page. If tests fail, the commit will be reverted to the previous one. It they succeed, the commit will be merged.

Test is made by running the command `pelican content --fatal=warnings`. This will generate static files so if there is an error in a data file it will stop.

You can see this configuration in .travis.yml.

**Comment by tomlemeuch** [comment]
Hello celine-m-s!
Thank you for this detailed answer.
Another last question(Yes I am very curious ;-) ): if Travis tests on a PR succeeded, who is commiting/merging the PR ?

**Comment by celine-m-s** [comment]
Well, it's a bit more complicated than that.
The commit is merge into master by you when you accept the PR. No phantom is involved! ;-) Then, we had to use a workaround to publish to the gh-pages branch automatically so that users could have their new profile on [the website](https://openclassrooms-student-center.github.io/alumnis/).
To do that, @regisb and I used a Makefile and a deploy key ([have a look](https://github.com/OpenClassrooms-Student-Center/alumnis/blob/master/Makefile)). As it's his key, he is deploying automatically to the gh-pages branch when a PR is merged into master.

**Comment by tomlemeuch** [comment]
Hello again!
You wrote : 
> The commit is merge into master by you when you accept the PR. 

But After Travis tests succeed , Github displays :

>This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests. 

See my PR [https://github.com/OpenClassrooms-Student-Center/alumnis/pull/595](https://github.com/OpenClassrooms-Student-Center/alumnis/pull/595) for example.

I don't understand how i can accept the PR by myself.
I'm sorry to be so insistent but i'm asking questions about this alumnis repo and PR approval to my  mentor since project 2 (i'm working on project 7 today) and i never got answers.
That's why i make use of your kindness ;-).

**Comment by celine-m-s** [comment]
Hello Tom!
No problem, I like answering questions! ^_^
You need to be a mentor to accept a request. If you're an alumni, you cannot (it would be too easy!). But I can accept your PR if your mentor is ok with that.

All mentors are part of a dedicated group within this organization. Only members of this group has the ability to accept PR.

**Comment by celine-m-s** [comment]
Sooooo...
I just changed small things in the Travis config file so that users can see *why* tests are failing directly in the PR page. Could you do a test for me? Just cancel you current PR and do a new one. I'd like to see if a message appears in the page. Then I can merge it for you if you want! ;-)

**Comment by tomlemeuch** [comment]
Hello Céline,
I just cancel my previous PR and make a new one as you asked. Hope that it can help you in your tests.
new PR: [https://github.com/OpenClassrooms-Student-Center/alumnis/pull/621](https://github.com/OpenClassrooms-Student-Center/alumnis/pull/621)

Travis tests are OK.

I would  be glad that you accept my PR.

Thank you.

**Comment by tomlemeuch** [comment]
Céline,
Thank you for merging my PR.
Do i have to close this issue or do you need me to make some tests for your Travis config?

**Comment by celine-m-s** [comment]
You can close it if you think we're done with this topic!

**Comment by tomlemeuch** [comment]
Ok, i close it,  thank you for your help.
