### ISSUE TITLE
Empty images are shown

### ISSUE THREAD

**Issue by celine-m-s** [OpenClassrooms-Student-Center/alumnis#630]
We should see a default image if an profile image cannot be shown on the index page and on the profile. Now, we can see we should have an image but it's broken. Not very pretty! ;-)

I suggest to do it in Javascript but feel free to submit what you think might be a good solution!

**Comment by celine-m-s** [comment]
See #629

**Comment by tomlemeuch** [comment]
@celine-m-s 
I propose #633 .

**Comment by celine-m-s** [comment]
I like this solution, compact and elegant. Just merged it.

**Comment by celine-m-s** [comment]
Huuuuum
I just tested it and it does not work on production.
URL should be: `https://openclassrooms-student-center.github.io/alumnis/images/oc-logo.svg` and not just `/images/oc-logo.svg` as root is `https://openclassrooms-student-center.github.io/alumnis`. Can you change it in your PR please?
Thanks!

**Comment by tomlemeuch** [comment]
Ok i will change my PR.

**Comment by tomlemeuch** [comment]
you already merge #633. so i make a new one : #642

**Comment by celine-m-s** [comment]
It works perfectly now. Thank you **so much** for your contributions!

**Comment by tomlemeuch** [comment]
@celine-m-s , thank you for your advises.
I'm glad I helped.
